language: node_js
node_js:
- stable
before_script:
- npm i -g mocha
- npm i -g istanbul
- npm i -g eslint
script:
- npm run eslint
- istanbul cover _mocha -- -R spec --recursive
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key:
    secure: TkdHJAv72ZoQYRjCHFtplBJyqIFa5chqeJVy8+xMrXeUIXuf3CKqa9v7xokK0obEzgdgiuF/8qP0uWT8XDVYY2dUI1QF4QAIrFiO81B13WrHEdQcH9piwWZd71jPa4kKe3OYzXwUnN/UPXMyb78sV22LkY817zGF/6aCggEIpZemEOWR37o5ugwGjGKLdFxTqR1WtCuSPH6oYLVEEJI5PTtPAAwFEZs3uYdDphR+VnMWmDp79xwaRsd53HlFvunMGqnksmcwFAzBrdPKokRR+Zd/K0njl6SSHaiiOlJherVaF5yTQMWixabaKrxLJePVNZUaeRF863o+l2q+Wgnxue60OStHQGcQUPkx3A6MCtioIvp0Ewe+eHmKj4/amXGAZCof/+OUv+6BvJsLVMnUxG9VVMD9Bqpkc+xs9ma8AxNFgrk4UgtErOInaLf6Jf181bI6xcBk/q43wzUTPEHeo9x3AgLOX9F0wUfoKbLAarULV8QLZ2v56zo89Y33L2dEOUU8ywUoCPLYcJLD/V3ua15ZG5NdfXSrC2E6Uq4xrpl6RUHD0rx5ubUWX6Mnch1KAmJ+3tf6Bq8PvOS37dCuhssWuB03HXYqKMQ9vXcyQW59D6aUYUdgQF1mFey2CW6w46YR2Jrn1xH41CNOXeko7LCWH3vb/whebBbTLUPqq80=
  app:
    develop: dev-fd-skype-bot
    master: prd-fd-skype-bot