language: node_js
node_js:
- stable
before_script:
- npm i -g mocha
- npm i -g istanbul
script:
- istanbul cover _mocha -- -R spec --recursive
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  app:
    develop: dev-fd-skype-bot
    master: prd-fd-skype-bot
  api_key:
    secure: o3L3VL1mlULY9Pnxanp7MFIP42wx0jufX5LgAIblnB9OPVI1a2ISVh6u1FKw6RQVhbwQSqPkMYI/r4ma8Fn5PXwfNBnzcJYCQI0UFfGbE7i3c8nYS0jy+h85X2+wrDbFBNgfzFjtj8a4jVzZppmyZ+KOxwLXpja4hBIHbQWWiikEoz3FjJtOhEp6S249YrKQrh08XNC+1lSA/HLG6EMQyqCYWWFERhtZi28+NR8KpggjynYvo9nhDfavcT2roY5+MSmrq0bnSfGp+VatNxTxj28OIJ5hd4RA696sqT6iLVHQwGR+Q7zvc6Hgvr5P4uIKN7MJXdesvb6rzd2+Fim9DuIuZEZmvochpFtKxIGX94lgPFI5A/CrnJPKn4L+8tttewenP1lVVnB274Ld36c4QqCl+k79Ew7yoz9p46f7qhkBuO2tc+UYC91rKXxC8hqdSGyAsEzuC1wefOixnX7qAHtasr5IMAQgyDmE1PE12QzWZN3jOKAP3IFaOOaEeWNa+AZmTWHmW5qJR5UNAphTQu5VoPReIet3liUSsAvoQWlhiTum86lDpqhsPjzCGIEUNlvXrQNNZZb7OIboMwpl3xg2hRpWWUG7JzpFcr6mVScdLx0eSs50UW6QPmxh4RLQx/B+4ihSV3PdyMtF5RlC46G7nO+ePVaS8MzFy6ps1Gk=
