language: node_js
node_js:
- stable
before_script:
- npm i -g mocha
- npm i -g istanbul
script:
- istanbul cover _mocha -- -R spec --recursive
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  app:
    develop: dev-fd-skype-bot
    master: prd-fd-skype-bot
  api_key:
    secure: PVdRwMMTd5pDLRmqaQ29/Ii/T/1z6XJ4P8mhsMDxFsXTIHAWos3R23FXrJ1sqenFhStsi+oXzdamQumQvdWmGzQZ9XOH4CR5dP+kbxpwxUwzBNX7zgi82LYh/3ZgVXQZQxw/zDsX1M5tx2GogyyOkzOOw6GGhFgSkRNl0bjYjxsbVKFfVwG+3tmrhdf5ia/Jk91jQfVkcSF3D2Y3Bu9gmvNtfq8h9kDtKZkc+23hypPqcmMH1EroEqB2UHFdoVguSsKt2bVdxFvORWG0Rg/l3ee5dlfQeZBBTpBS/cBzvxv5jv7IpnMm9pExt+/g8Zt80lOPvqbxG1Rmj+9chA0T37U6l7HqKKHfI1EwMHn+XUa8B3UPiMqJEMsUpkqLgcuIP/WGgnVh8eycXBdgqMy5UfSNs4nuyYc2voug+5uPVymdrG6dSCJfJHK+zfZyYBNVsYbqf79Pg9tAQObH09JpvIOdgz10IW1Fp+97NUPiGuvHwDJj03b98lMNAls75VuJkcGAlYwpNPzvwc1dCC2QUd4yoX7CgyX2kwhbDrY4CJO/AsPwKi9E2wBOqy+2LcsmzUf/6zqDTZ68Xs+ADNJpeTRgFxVnx6KK1v2FfkfUiD/yToyAYKTHzquhBawNDdRKM3v9ZneLdTa70RH6pHGeCdiYfCppfxsVsSPRwG+n+EE=
